/**
 * Communication Subscribers
 *
 * Event-driven communication integrations. Each function below
 * registers handlers on the internal event bus. When an event fires,
 * the matching handler sends emails, SMS, pushes, CRM syncs, etc.
 *
 * ─── Extending ────────────────────────────────────────────────────────
 *
 * Add new event subscriptions inside the relevant init function (or
 * create a new one). The pattern is always the same:
 *
 *   eventBus.subscribe(EventType.YOUR_EVENT, async (payload) => { … });
 *
 * Entity-specific events generated by BaseService follow the format
 * "{ENTITY}_CREATED", "{ENTITY}_UPDATED", "{ENTITY}_DELETED" and can
 * be subscribed to by casting the string: `'ORDER_CREATED' as EventType`.
 */

import { eventBus, EventType } from '../utilities/events';
import { getEmailConnector } from '../utilities/email-connector';
import { getSMSConnector } from '../utilities/sms-connector';
import { getCRMConnector } from '../utilities/crm-connector';
import { getRealtimeConnector } from '../utilities/realtime-connector';
import { getPushNotificationsConnector } from '../utilities/push-notifications-connector';
import { getNotificationInboxConnector } from '../utilities/notification-inbox-connector';
import { logger } from '../utilities/logger';

/**
 * Initialize all communication event subscribers.
 * Call this once during application startup (e.g. in index.ts).
 */
export function initializeCommunicationSubscribers(): void {
  initializeEmailNotifications();
  initializeSMSNotifications();
  initializeCRMSync();
  initializeRealtimeUpdates();
  initializePushNotifications();
  initializeNotificationInbox();

  logger.info('Communication subscribers initialized');
}

/**
 * Email Notifications — send transactional emails based on events
 */
function initializeEmailNotifications(): void {
  const emailConnector = getEmailConnector();
  if (!emailConnector) {
    logger.debug('Email connector disabled, skipping email notifications');
    return;
  }

  // Example: Send welcome email when a user is created
  eventBus.subscribe(EventType.USER_CREATED, async (payload) => {
    try {
      const userData = payload.data as any;
      await emailConnector.sendTransactional({
        to: [{ email: userData?.email, name: userData?.displayName }],
        templateId: 'welcome-email',
        variables: {
          firstName: userData?.firstName || 'there',
          loginUrl: `${process.env.APP_URL}/login`,
        },
        tags: ['welcome', 'transactional'],
      });
    } catch (error) {
      const err = error instanceof Error ? error : new Error(String(error));
      logger.error('Failed to send welcome email', err);
    }
  });

  // Add more email handlers here as your event catalogue grows
}

/**
 * SMS Notifications — send SMS based on events
 */
function initializeSMSNotifications(): void {
  const smsConnector = getSMSConnector();
  if (!smsConnector) {
    logger.debug('SMS connector disabled, skipping SMS notifications');
    return;
  }

  // Example: Phone verification
  // eventBus.subscribe('PHONE_VERIFICATION_REQUESTED' as EventType, async (payload) => {
  //   await smsConnector.sendMessage({
  //     to: payload.phoneNumber,
  //     message: `Your verification code is: ${payload.code}`,
  //     tags: ['verification'],
  //   });
  // });
}

/**
 * CRM Sync — sync data to CRM systems
 */
function initializeCRMSync(): void {
  const crmConnector = getCRMConnector();
  if (!crmConnector) {
    logger.debug('CRM connector disabled, skipping CRM sync');
    return;
  }

  // Example: Create contact in CRM when a user is created
  eventBus.subscribe(EventType.USER_CREATED, async (payload) => {
    try {
      const userData = payload.data as any;
      await crmConnector.createContact({
        email: userData?.email || '',
        firstName: userData?.firstName,
        lastName: userData?.lastName,
        source: 'web_app',
        customFields: {
          signup_date: payload.timestamp,
          user_role: userData?.role,
        },
        tags: ['new-user'],
      });
    } catch (error) {
      const err = error instanceof Error ? error : new Error(String(error));
      logger.error('Failed to sync user to CRM', err);
    }
  });

  // Add more CRM sync handlers here
}

/**
 * Realtime Updates — broadcast events to connected clients via SSE / WebSocket
 */
function initializeRealtimeUpdates(): void {
  const realtimeConnector = getRealtimeConnector();
  if (!realtimeConnector) {
    logger.debug('Realtime connector disabled, skipping realtime updates');
    return;
  }

  // Broadcast every known event type to connected clients.
  // Entity-specific events (ORDER_CREATED etc.) can be added
  // individually as they are defined.
  Object.values(EventType).forEach((eventType) => {
    eventBus.subscribe(eventType, async (payload) => {
      try {
        await realtimeConnector.broadcast({
          id: `${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
          type: eventType,
          data: payload,
          timestamp: new Date(),
        });
      } catch (error) {
        const err = error instanceof Error ? error : new Error(String(error));
        logger.error('Failed to broadcast realtime update', err, {
          eventType,
        });
      }
    });
  });
}

/**
 * Push Notifications — send mobile / web push notifications based on events
 */
function initializePushNotifications(): void {
  const pushConnector = getPushNotificationsConnector();
  if (!pushConnector) {
    logger.debug('Push notifications connector disabled, skipping push notifications');
    return;
  }

  // Example: Send push notification when user is mentioned
  // eventBus.subscribe('USER_MENTIONED' as EventType, async (payload) => {
  //   try {
  //     await pushConnector.send({
  //       target: { token: payload.data?.deviceToken },
  //       notification: {
  //         title: 'You were mentioned',
  //         body: `${payload.data?.mentionedBy} mentioned you in a comment`,
  //         clickAction: `${process.env.APP_URL}/comments/${payload.data?.commentId}`,
  //       },
  //       options: { priority: 'high' },
  //     });
  //   } catch (error) {
  //     logger.error('Failed to send push notification', { error });
  //   }
  // });

  // Add more push notification handlers here
}

/**
 * Notification Inbox — persist notification records for REST and realtime delivery
 */
function initializeNotificationInbox(): void {
  const inboxConnector = getNotificationInboxConnector();
  if (!inboxConnector) {
    logger.debug('Notification inbox connector disabled, skipping');
    return;
  }

  // Example: Welcome notification when a user is created
  eventBus.subscribe(EventType.USER_CREATED, async (payload) => {
    try {
      const userData = payload.data as any;
      await inboxConnector.writeNotification({
        userId: userData?.id || payload.entityId || '',
        type: 'system',
        title: 'Welcome!',
        body: 'Your account has been created successfully.',
        sourceEvent: EventType.USER_CREATED,
        actionUrl: '/dashboard',
      });
    } catch (error) {
      const err = error instanceof Error ? error : new Error(String(error));
      logger.error('Failed to write inbox notification for USER_CREATED', err);
    }
  });

  // Add more event -> notification mappings here
}
